### ISSUE TITLE
Disable developer mode extensions

### ISSUE THREAD

**Issue by abderrahmane-tj** [AllMangasReader-dev/AMR#127]
Starting 14th of Mai, Google chrome started showing "Disable developer mode extensions" even in dev channel. I know this is Google Chrome related, and I should investigate in the other end of the tunnel, but what are your thoughts ?

Is this the end ? :/

What a beautiful journey it has been !

**Comment by stardisblue** [comment]
I'm currently using opera ;)

**Comment by mexicano21** [comment]
Can you install Chrome extensions in Opera...?

2015-12-16 21:55 GMT-02:00 stardisblue <notifications@github.com>:

> I'm currently using opera ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AllMangasReader-dev/AMR/issues/127#issuecomment-165289737>
> .
>



-- 
Fábio de Godoy
http://anime21.blog.br
http://www.guiadosquadrinhos.com/capas-dos-gibis-da-colecao/godoy-rodrigues-da-silva/45583

**Comment by abderrahmane-tj** [comment]
sure, they started using almost same core Blink Web Engine back in 2013
https://en.wikipedia.org/wiki/Blink_(web_engine)

On 17 December 2015 at 00:14, mexicano21 <notifications@github.com> wrote:

> Can you install Chrome extensions in Opera...?
>
> 2015-12-16 21:55 GMT-02:00 stardisblue <notifications@github.com>:
>
> > I'm currently using opera ;)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/AllMangasReader-dev/AMR/issues/127#issuecomment-165289737
> >
> > .
> >
>
>
>
> --
> Fábio de Godoy
> http://anime21.blog.br
>
> http://www.guiadosquadrinhos.com/capas-dos-gibis-da-colecao/godoy-rodrigues-da-silva/45583
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AllMangasReader-dev/AMR/issues/127#issuecomment-165296500>
> .
>



-- 
Abderrahmane TAHRI JOUTI
(+212)  6 33 14 97 99

**Comment by mexicano21** [comment]
I know they use same engine, but I thought that the addon subsystem could
be different, even if only slightly. Well, I started using Opera two months
ago, I think it's time to resuscitate my AMR. Thanks =)

2015-12-16 22:16 GMT-02:00 Abderrahmane TAHRI JOUTI <
notifications@github.com>:

> sure, they started using almost same core Blink Web Engine back in 2013
> https://en.wikipedia.org/wiki/Blink_(web_engine)
>
> On 17 December 2015 at 00:14, mexicano21 <notifications@github.com> wrote:
>
> > Can you install Chrome extensions in Opera...?
> >
> > 2015-12-16 21:55 GMT-02:00 stardisblue <notifications@github.com>:
> >
> > > I'm currently using opera ;)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/AllMangasReader-dev/AMR/issues/127#issuecomment-165289737
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Fábio de Godoy
> > http://anime21.blog.br
> >
> >
> http://www.guiadosquadrinhos.com/capas-dos-gibis-da-colecao/godoy-rodrigues-da-silva/45583
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/AllMangasReader-dev/AMR/issues/127#issuecomment-165296500
> >
> > .
> >
>
>
>
> --
> Abderrahmane TAHRI JOUTI
> (+212) 6 33 14 97 99
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AllMangasReader-dev/AMR/issues/127#issuecomment-165297094>
> .
>



-- 
Fábio de Godoy
http://anime21.blog.br
http://www.guiadosquadrinhos.com/capas-dos-gibis-da-colecao/godoy-rodrigues-da-silva/45583

**Comment by mikeyjm145** [comment]
It works great on opera. Chrome officially shut down any chance of having non-store chrome apps. Opera is your only option. Although, you can make your own internet browser / desktop app that centers around AMR to continue development if you want to take it that direction.

**Comment by bowentay** [comment]
Just to clarify, non-Store Chrome extensions still work, Chrome just shows a "Disable developer mode extensions" popup on every startup, and there are no current plans to remove that popup due to abuse issues.

[See this Chromium bug report for more details](https://bugs.chromium.org/p/chromium/issues/detail?id=337734#c4)
