### ISSUE TITLE
Cannot enable on Chrome

### ISSUE THREAD

**Issue by zaynv** [AllMangasReader-dev/AMR#134]
**Chrome:  Version 50.0.2661.102 (64-bit)**

For some reason, when I drag the `.crx` file into the `chrome://extensions/` page, this is the result:

<img width="748" alt="screen shot 2016-05-15 at 6 10 54 pm" src="https://cloud.githubusercontent.com/assets/8627403/15277122/66235c2c-1ac8-11e6-9be4-7d3bd828aafb.png">

As you can see, it is grayed out and pressing the **Enable** checkbox doesn't work. Any help would be appreciated.

**Comment by stardisblue** [comment]
it's chrome policies, you can't install external extension in chrome, you'll need to change the browser to something else (Chromium, Opera .... )

**Comment by zaynv** [comment]
I was able to find a workaround:

1. Change the installed file from a `.crx` into a `.zip`.
2. Unzip the file into a folder.
3. In the `chrome://extensions/` page, click the **Load unpacked extension...** and then just open the folder you you unzipped everything into.

The extension should work after that.
