### ISSUE TITLE
Putting this extension on Google Chrome Extension Store

### ISSUE THREAD

**Issue by zaynv** [AllMangasReader-dev/AMR#135]
Is there a reason that this extension cannot be put onto Google's Chrome Extension Store? That would solve a lot of issues for people that keep having the `Disable Developer Mode Extension` popup that always comes when you start Chrome. I would be happy to donate the money for the developer signup fee.

**Comment by braiam** [comment]
The Chrome Store pulled the extension out for "helping the access to material (scans) which violate intellectual property", and is doubtful that we could enter it again.
