### ISSUE TITLE
Batoto giving alerts for different languages

### ISSUE THREAD

**Issue by Toonv5** [AllMangasReader-dev/AMR#139]
When i read on batoto, the chapters stay the same language, but i get alerts if a manga gets a new chapter in another language. Or when i continue reading, chapters in another language get mixed in aswell.. Is it possible to filter out those languages?

I've gotten baited a couple of times where i got hyped about seeing a new chapter, just to see that it's a new translation in spanish that i cant read.

**Comment by DakuTree** [comment]
Try switching the language options on the sidebar on the front page. Bato.to defaults to showing all languages by default which makes it a bit tricky to grab the proper chapter list.

**Comment by Toonv5** [comment]
Ah, thanks. I was looking for a setting like that in the account settings but couldn't find it.
