### ISSUE TITLE
Always center the image

### ISSUE THREAD

**Issue by andrew-tc** [AllMangasReader-dev/AMR#144]
On some sites (e.g. www.mangahere.co), if there are pages with different sizes in same chapter, the images will be shown left-aligned. It looks like there's a fixed left margin.

Other sites (e.g. www.mangafox.com) don't seem to have this problem though.

PS. is it a site-specific issue?

**Comment by braiam** [comment]
This is issue of the script that manage that specific site https://github.com/AllMangasReader-dev/mirrors/blob/master/MangaHere.js. Check the doSomethingBeforeWritingScans function and whereDoIWriteNavigation.
