### ISSUE TITLE
Mangafox don't load images correctly

### ISSUE THREAD

**Issue by lcangelica** [AllMangasReader-dev/AMR#145]
![image](https://cloud.githubusercontent.com/assets/24394969/20897216/7eaf26d2-bb08-11e6-9568-9a38db4411f1.png)
If I use AMR with the option of displaying the whole chapter mangafox don't work properly but if I use the option of showing only one page it works.

**Comment by Deus-Rex** [comment]
Same issue here.

**Comment by braiam** [comment]
Check https://github.com/AllMangasReader-dev/mirrors/blob/master/MangaFox.js , as it's most likely an issue with the mirror.
