### ISSUE TITLE
Pull request to correct MangaFox problem

### ISSUE THREAD

**Issue by typhoe** [AllMangasReader-dev/AMR#146]
Hi,

I have created a [pull request](https://github.com/AllMangasReader-dev/mirrors/pull/26) in the "Mirrors" repository to correct the actual problem with the MangaFox mirror.
As there doesn't seem to be any activity in that repo, I also post this message here.

Thank you.

**Comment by braiam** [comment]
I think everyone on the organization are notified of every change on any of the repositories by default.
