### ISSUE TITLE
503 error coming up

### ISSUE THREAD

**Issue by sleepingdemon1996** [AllMangasReader-dev/AMR#147]
when i use asmr on mangafox it only loads 3 pages for any manga and gets stuck loading the rest since jan/4/2017

**Comment by braiam** [comment]
503 errors are server side, nothing to do with us. https://httpstatuses.com/503

**Comment by sleepingdemon1996** [comment]
the website stopped having 503 errors but the extension still only load 14% of the chapter and gets stuck
