### ISSUE TITLE
AMR on Mangastream/Readms.net

### ISSUE THREAD

**Issue by SilverZCrow** [AllMangasReader-dev/AMR#152]
Hello,

AMR is working on mangstream.com, however **when I open any chapter in Mangastream.com the URL changes to Readms.net, causing AMR not to function.**

Is there a way to add Readms.net to a list to make AMR work on it?

Thanks.

**Comment by braiam** [comment]
This is a mirror's problem, please report it there https://github.com/AllMangasReader-dev/mirrors
