### ISSUE TITLE
AMR unable to update progress for any batoto chapters

### ISSUE THREAD

**Issue by Snipeon** [AllMangasReader-dev/AMR#153]
Hi, it seems that AMR has given up on tracking the progress of all Batoto manga chapters. The manga still adds just fine, however the chapter progress is messed up, with AMR showing either the first or last chapter in the series. Even showing the last chapter still has it marked as unread. Deleting the manga from AMR and adding it again does not work, the problems above still persist.

**Comment by Churba** [comment]
Having the same problem. Viewing the Manga seems to just add a second entry for it, which is also unread, in the same way it would if you were adding the same Manga from a different source.
It's also refusing to display last read chapter for me on the chapter list, it just leaves that space blank.

Chapter progress seems fine for me, the read last read button takes me to the appropriate chapters reliably.

**Comment by Vesnyx** [comment]
Issue might be due to bato.to having https now.

**Comment by Churba** [comment]
Bearing in mind that I'm a bit stupid when it comes to these sorts of things, what sort of thing needs to be done to fix it? Is it terribly complex, or is it something even a twit like me could manage?

**Comment by gendouhydeist** [comment]
Honestly this project has been long dead, no one's is maintaining it.

**Comment by braiam** [comment]
@Vesnyx No, the code doesn't assume that only http url are expected, that was fixed over a year ago https://github.com/AllMangasReader-dev/mirrors/commit/0273044f561ff3db8819ed31e78226890cc2bfc1.

@Churba someone with the drive, time and knowledge to at very least identify a reason. There isn't a reason why this would happen as it's the _exactly same code_ that we use to track everything else. If Batoto changed something, it would need someone to actually test it.

The specific file is here https://github.com/AllMangasReader-dev/mirrors/blob/master/Batoto.js, take a look at it. You can use lab to check out what's the extension doing. If anyone can find the issue, open an issue on that repository.
