### ISSUE TITLE
Mangafox change their domain !

### ISSUE THREAD

**Issue by king37sniper** [AllMangasReader-dev/AMR#160]
Mangafox change their domain from .me to .la
And now it completely broken 
I can't read and add new manga, we need a new update
But, i don't think main dev is active rightnow, he offline around 4 months ?

**Comment by king37sniper** [comment]
If money is problem, can we pay to use???, i just want this plugin working 4ever

**Comment by monkey8113** [comment]
If a dedicated dev willing to take over the project, Look after and improve this plugin. Maybe make it a standalone program. I would pay for this

**Comment by king37sniper** [comment]
Yeah, i will buy it for sure

**Comment by xietbrix** [comment]
I would buy/subscribe too!

Maybe all of us should just kickstart a fund to get some developer to do it for us :P

**Comment by xietbrix** [comment]
side note, does anybody know definitively what the list of manga sites that still work with AMR?

i know mangareader and manga panda still work, so i'm going to start transferring my manga over to those from mangafox. any other ones?

**Comment by king37sniper** [comment]
Mangahere still working

**Comment by xietbrix** [comment]
Nice thanks for that. Going to try spreading the manga around the three remaining sites to mitigate the next damage we receive :(

**Comment by king37sniper** [comment]
I email the main developrer (braiam), but he's not responding  
We still need him to officially transfer the source code, we can't just take it away and hire another dev to continue progress
Is that right?

**Comment by EndOfFile** [comment]
I did fix the issue for myself but to fix it for everyone braiam is needed.

The two files you have to change the mangafox URL in are [websites.json](https://github.com/AllMangasReader-dev/mirrors/blob/master/websites.json) and [MangaFox.js](https://github.com/AllMangasReader-dev/mirrors/blob/master/MangaFox.js).

The next problem is how to get these new files into AMR.
AMR loads the mirror files automatically from [mirror](https://community.allmangasreader.com/latest_v2/) which makes it harder for us to just change these files locally.

If you want to fix it locally for yourself you can do the following:
**NOTE: You will lose all your AMR settings**

1. **BACKUP YOUR MANGAS**: Use the export function of AMR to backup your mangas to a textfile.
2. Open the textfile and replace all mangafox.me by mangafox.la
3. Uninstall the AMR extension
4. Download the AMR repo to your computer into a folder named AMR
5. Download the mirror repo [mirrors](https://github.com/AllMangasReader-dev/mirrors) and change mangafox.me to mangafox.la in **websites.json** and **MangaFox.js**
6. Now setup a http server to serve these files to AMR as mentioned by the dev [here](https://github.com/AllMangasReader-dev/mirrors/issues/9)
For that i used python3: open a terminal in the mirror repo folder and execute **python3 -m http.server** which serves these files to localhost:8000
7. Point AMR to the local repo by changing in **AMR/js/mgEntry.js** the variables **amrc_repository**, **amrc_root** and **amrc_repository_backup** to **http://localhost:8000/**
And change the **validURL()** function bellow them to allow http by changing **https** to **http**
8. In **AMR/manifest.json** change the line that starts with **content_security_policy** by adding **http://localhost:8000/** to the list URLs
9. In chrome click load unpacked extension and point it to the AMR folder. (Webserver should know get requests from it)
10. Next go to mangafox.la and test if it works
11. Import your mangas back into AMR
12. Shutdown the webserver. AMR did download all mirror files into itself so it isn't needed anymore (or only if you want to update some mirror files again)

**Note**: AMR now only uses your local mirrors and doesn't get updates from AMR anymore

**Comment by king37sniper** [comment]
Oh fuck, ty @EndOfFile, i forgot that (https to http) part 
Lost 1 day try to fix it myself and i'm going github to cry
Now i can relax and keep reading manga and wait braiam comeback =))

**Comment by xietbrix** [comment]
Ty for the instructions! I'll definitely be going through that myself at some point too.

**Comment by monkey8113** [comment]
@EndOfFile could you help upload the fixed file here? It would helps a lot with a simple upload.
btw you could submit a pull request, if braiam seen it he could approve it. 

p/s: if i wanted to add new website support to it myself. could i copy mangafox data from mangafox.js and website.json and replace mangafox website to the new website?

**Comment by Stubbs9410** [comment]
can someone put the entire AMR with fixes and put in a archive pls because i have problems with fixing what @EndOfFile said cant find all files in my AMR folder. 
Thanks anticipated.

**Comment by king37sniper** [comment]
Export ur manga : chrome-extension://nhjloagockgobfpopemejpgjjechcpfd/importexport.html
.
Download and install XAMPP : https://www.apachefriends.org/xampp-files/5.6.32/xampp-win32-5.6.32-0-VC11-installer.exe
.
Then click config in module Apache : https://i.imgur.com/hsvisTp.png
Notepad will open, change "Listen" to 8000  : https://i.imgur.com/qUWXeJZ.png
.
Start  module Apache
.
Download this : https://drive.google.com/open?id=1VdnIS9PzINW2NfuUavjtz2UN4dWAj4WB
Extract js.zip to C:\xampp\htdocs
Extract AMR.rar to everywhere u want
.
Go chrome://extensions/ click load unpacked extension and point it to where u extract AMR.rar
.
Done, u can quit XAMPP now, if sometimes AMR didn't work, Reopen XAMPP start Apache module and reload AMR extensions on chrome
.
Import ur manga and start reading

**Comment by xietbrix** [comment]
just learned the hard way that chrome extensions will only accept https connections to anything except localhost. so don't bother trying to host the mirrors on a webhost unless you're willing to go through CSR signing for the SSL certs process as well.

**Comment by xietbrix** [comment]
I noticed after doing all the above to fix things, that the chapters aren't being automatically being marked as read anymore, even after i've loaded the chapter 100%. I have to manually click the Eye icon to mark it as read.

is anybody else experiencing this problems?

**Comment by king37sniper** [comment]
That's a bug, happened a very long time ago in mangahere, mangafox
Mangareader still working fine

**Comment by monkey8113** [comment]
Happens to me too now. Mangafox don't have this problem before. Could it be the page for at is different? Now it's page /(manga)/1.html instead of /(manga)/1

**Comment by king37sniper** [comment]
No, it's here https://github.com/AllMangasReader-dev/AMR/issues/156

**Comment by xietbrix** [comment]
oh yeah, it must've been working for me before because i was using twluo's fixed version. i can't continue to use twluo's version now because it will forcibly change http to https, and mangafox no longer supports https so it all breaks. 

that's unfortunate.

**Comment by Stubbs9410** [comment]
it's loading manga, but now i can't add new manga from that site(mangafox.la). Does somebody know how to load manga from mangafox?
Sorry for the inconvenience.

**Comment by braiam** [comment]
Changes to mirrors should be reported/fixed on the mirrors repository. https://github.com/AllMangasReader-dev/mirrors

**Comment by xietbrix** [comment]
hmmm, i'm using the original 1.5.10.2 AMR and it's not working for mangafox.la.

is the mirrors really updated?

EDIT: I should clarify that mangareader is working fine, but the extension doesn't load for mangafox.la (i.e. the navigation bar at the top doesn't appear, ads are showing, the entire chapter isn't loading etc).

**Comment by king37sniper** [comment]
No,it isn't updated

**Comment by xietbrix** [comment]
oh i see. is it possible to move this back into open issue?

**Comment by king37sniper** [comment]
I created a new pull request, waiting braiam to review and commit

**Comment by monkey8113** [comment]
I don't see any open pull request?

**Comment by king37sniper** [comment]
https://github.com/AllMangasReader-dev/mirrors/pull/35

**Comment by king37sniper** [comment]
My god, braiam
Seriously, he only online to close this thread ?

**Comment by monkey8113** [comment]
@king37sniper I cant get mine working, do i need the original AMR or twluo fix version will work?

**Comment by king37sniper** [comment]
original AMR and twluo ver will not working, mine and EndOfFile work

**Comment by braiam** [comment]
Lets repeat again, issues about mirrors in the repository for mirrors.
