### ISSUE TITLE
Mangahere change domain

### ISSUE THREAD

**Issue by noodle27** [AllMangasReader-dev/AMR#161]
Long story short: they jumped again from .co to .cc. Can anyone make a fix for this? I know there's a similar issue of Mangafox changed their domain and someone put a solution there, but I'm completely alien to coding and stuck at the point of set up http server.

And yeah, I, too, am at the point of willing to pay to use AMR now.

**Comment by EduardKhudaiberdin** [comment]
I believe you will have to open the issue in appropriate git hub. Otherwise owner will just close it.

**Comment by noodle27** [comment]
@EduardKhudaiberdin This is not where we report issues? Can you show me where the right place pls?

**Comment by EduardKhudaiberdin** [comment]
Yes. But it should be about ARM. If you want to submit issue with mirror you should report it here https://github.com/AllMangasReader-dev/mirrors

**Comment by noodle27** [comment]
Oh, thanks.
