### ISSUE TITLE
AMR didn't show any of my mangas in the list

### ISSUE THREAD

**Issue by ryuuakagi** [AllMangasReader-dev/AMR#162]
it suddenly didn't show any mangas, tried reloading several times but it always shows an empty list. i didn't delete any of my hundreds of mangas manually or incidentally. how do i fix this?

**Comment by king37sniper** [comment]
Can u import ur manga ?

**Comment by ryuuakagi** [comment]
i do import an older version of it at the end. thankfully the sqlite db is intact and i can open it to see what mangas have i added after the timestamp of that backup list. 

is it maybe because of the localStorage suddenly got emptied? is it maybe a chrome issue?

**Comment by king37sniper** [comment]
U should backup ur manga list 
chrome-extension://nhjloagockgobfpopemejpgjjechcpfd/importexport.html
.
AMR issue i think, but it's very rare, same thing happened to me 5 years ago

**Comment by ryuuakagi** [comment]
ahh alright. i now keep daily backup of my manga list. are there no solution to fix this?

**Comment by king37sniper** [comment]
My solution is try re-import my manga list :))
U still get that issue? manga list still empty ?

**Comment by ryuuakagi** [comment]
oh, no. i mean to prevent this from happening again. my current issue is solved by importing my older backup manga list. but are there no way to prevent this from happening again? except to mitigate it by keeping a backup of manga list, of course

**Comment by king37sniper** [comment]
I think yes, there is no current solution for this issue

**Comment by ryuuakagi** [comment]
ahh alright. solved then. i'll close this issue. thanks for the help
